global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken


frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-bonus2k.2sem.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix
  containerPort: 80
  image: bonus2k/sausage-store-frontend
  version: "latest"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgres:5432/sausage-store
    reportPath: /logs/reports
    logPath: /logs
  secret:
    vaultToken:
      name: sausage-store-secret
      key: VAULT_TOKEN
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
  ### Опишите стратегию RollingUpdate для бэкенда
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: bonus2k/sausage-store-backend
  version: "latest"
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
  ### Опишите LivenessProbe для бэкенда
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  vpa:
  ### Опишите VPA для бэкенда
    updatePolicy:
      updateMode: "Auto"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "100m"
            memory: "128Mi"
          maxAllowed:
            cpu: "1"
            memory: "512Mi"

backend-report:
### Опишите значения для backend-report
### Приложение должно использовать стратегию Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb. 
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report
  secret:
    mongodbUri:
      name: sausage-store-secret
      key: MONGODB_URI
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: Recreate
  image: bonus2k/sausage-store-backend-report
  version: "latest"
  imagePullPolicy: Always
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /api/v1/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3
  hpa:
    averageUtilization: 50
    minReplicas: 1
    maxReplicas: 3


infra:
  postgresql:
    env:
      POSTGRES_DB: sausage-store
    secret:
      postgresUsername:
        name: sausage-store-secret
        key: POSTGRES_USER
      postgresPassword:
        name: sausage-store-secret
        key: POSTGRES_PASSWORD
    containerPort: 5432
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  ### Опишите необходимые переменные для развертывания PostgresQL в кластере Kubernetes
  mongodb:
    secret:
      mongodbUsername:
        name: sausage-store-secret
        key: MONGO_INITDB_ROOT_USERNAME
      mongodbPassword:
        name: sausage-store-secret
        key: MONGO_INITDB_ROOT_PASSWORD
    containerPort: 27017
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
